projectId: app-xb2rWgbUQVQRyk5jGZNTQM
appName: order2
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 2
    minReplicas: 2
    maxReplicas: 2
    dockerImage: shenalisj/cart
    containerPort: 8080
  OrderService:
    serviceName: orderservice
    avgReplicas: 2
    minReplicas: 2
    maxReplicas: 2
    dockerImage: shenalisj/order
    containerPort: 8080
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 2
    minReplicas: 1
    maxReplicas: 2
    dockerImage: shenalisj/user
    containerPort: 8080
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
